// Code generated by "stringer -type=ParType"; DO NOT EDIT.

package fzn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParTypeUnknown-0]
	_ = x[ParTypeInt-1]
	_ = x[ParTypeBool-2]
	_ = x[ParTypeFloat-3]
	_ = x[ParTypeSetOfInt-4]
}

const _ParType_name = "ParTypeUnknownParTypeIntParTypeBoolParTypeFloatParTypeSetOfInt"

var _ParType_index = [...]uint8{0, 14, 24, 35, 47, 62}

func (i ParType) String() string {
	if i < 0 || i >= ParType(len(_ParType_index)-1) {
		return "ParType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParType_name[_ParType_index[i]:_ParType_index[i+1]]
}
