// Code generated by "stringer -type=SolveMethod"; DO NOT EDIT.

package fzn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SolveMethodSatisfy-0]
	_ = x[SolveMethodMinimize-1]
	_ = x[SolveMethodMaximize-2]
}

const _SolveMethod_name = "SolveMethodSatisfySolveMethodMinimizeSolveMethodMaximize"

var _SolveMethod_index = [...]uint8{0, 18, 37, 56}

func (i SolveMethod) String() string {
	if i < 0 || i >= SolveMethod(len(_SolveMethod_index)-1) {
		return "SolveMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SolveMethod_name[_SolveMethod_index[i]:_SolveMethod_index[i+1]]
}
